import "@styles/globals.css"
import ClientLayout from "@/components/global/clientLayout";
import type { Metadata } from "next";
import { DM_Sans, Poppins } from "next/font/google";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-main",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-secondary",
});

export const metadata: Metadata = {
  title: "Horizon Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${dmSans.variable} ${poppins.variable}`}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html> 
  );
}
