import ClientLayout from "@/components/global/clientLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Horizon Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="light">
      <body>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
